config:
  organization:organization:
    region: us-east-1
    managementAccountId: '302481198387'
  organization:identity:
    assumeRoleName: none
    adminsGroupId: b4b86408-e0d1-7003-ad26-1c66785c7f91
    developersGroupId: 8478f4c8-f011-706d-b199-73c569c9766f
    readOnlyGroupId: 9468c488-8091-7075-395f-8dcc10388575
  organization:accounts:
    staging:
      accountId: '135133927765'
      assumeRoleName: OrganizationAccountAccessRole
    production:
      accountId: '324793866424'
      assumeRoleName: OrganizationAccountAccessRole
    requested: []
  organization:guardrails:
    billingAlertEmail: platform-alerts@example.com
    ciCdPrincipalArn: arn:aws:iam::302481198387:role/PulumiOperatorRole
    staging:
      budgetLimitUsd: 150
    production:
      budgetLimitUsd: 500
  organization:imports:
    accounts:
      - key: cloudtrail-administrator-1691
        name: CloudTrail administrator
        id: '639098881691'
        parentKey: security
      - key: aggregator-account-4837
        name: Aggregator account
        id: '765151564837'
        parentKey: security
    policies:
      - key: aws-guardrails-veasrx-p-c8zu0d23
        name: aws-guardrails-VEaSrx
        id: p-c8zu0d23
        attachToKey: security
      - key: aws-guardrails-kxupwq-p-quyz3iax
        name: aws-guardrails-kXuPWq
        id: p-quyz3iax
