# docker build -f Dockerfile.sandbox -t aamini-stack-sandbox:v1 .
# docker sandbox run --load-local-template -t aamini-stack-sandbox:v1 claude .
# docker run --rm -it --entrypoint bash aamini-stack-sandbox:v

FROM debian:12-slim

RUN apt-get update  \
    && apt-get -y --no-install-recommends install  \
        # install any other dependencies you might need
        sudo curl git ca-certificates build-essential \
    && rm -rf /var/lib/apt/lists/*

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
ENV MISE_DATA_DIR="/mise"
ENV MISE_CONFIG_DIR="/mise"
ENV MISE_CACHE_DIR="/mise/cache"
ENV MISE_INSTALL_PATH="/usr/local/bin/mise"
ENV PATH="/mise/shims:$PATH"

RUN curl https://mise.run | sh

WORKDIR /home/agent/project
COPY . .
RUN mise trust
RUN mise i

