FROM mcr.microsoft.com/playwright:v1.59.1-noble AS e2e
ARG APP_NAME
ENV COREPACK_ENABLE_DOWNLOAD_PROMPT=0
RUN corepack enable && corepack install -g pnpm@10.29.3
WORKDIR /app
COPY --from=installer /app /app
COPY apps/${APP_NAME}/playwright.config.ts /app/apps/${APP_NAME}/playwright.config.ts
COPY apps/${APP_NAME}/e2e /app/apps/${APP_NAME}/e2e
WORKDIR /app/apps/${APP_NAME}
ENTRYPOINT ["pnpm", "playwright", "test", "--config=playwright.config.ts"]
