config:
  aws:region: us-east-1
  aamini-infra:kubernetes:
    clusterName: aamini-staging
    version: '1.31'
    instanceType: t3.large
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    endpointPublicAccess: true
    endpointPrivateAccess: false
  aamini-infra:flux:
    ociRepository: oci://302481198387.dkr.ecr.us-east-1.amazonaws.com/projects-gitops
    ociTag: latest
  aamini-infra:fluxOperator:
    githubRepository: aamini-stack/projects
    githubSecretName: github-operator-auth
  aamini-infra:githubActionsOidc:
    enabled: true
    roleName: github-actions-ecr-publish
    repo: aamini-stack/projects
    allowPullRequest: true
    allowedRefs:
      - refs/heads/main
  aamini-infra:postgresProvider: aws
  aamini-infra:postgres:
    instanceClass: db.t4g.micro
    allocatedStorage: 20
    maxAllocatedStorage: 100
    backupRetentionDays: 7
    engineVersion: '16.3'
    storageType: gp3
    publiclyAccessible: false
    deletionProtection: false
    multiAz: false
    allowedCidrs:
      - 10.0.0.0/8
  github:token:
    secure: AAABAEn5sQBN8aOyIdo5XwUwiG7GJ5Ph+lw1YXhzmkKt6M7iLbNqcSpyBt7IUUQUNTI4qp99/7bhEvgNA+/k4eXcbCUEMirDrzHUmhQdbWwpCUuW+ZgONSohQUBq1d80L2PUjSBdmTWT2sQTg8+ayNs7OWpdm1iveU7ZZro=
  aamini-infra:postgresAdminPassword:
    secure: AAABAKE91IagSDI/hctrf8si0Kt7aJ62MFl/vSIJu0zEIZPpd+lCTG8YumF/N7rv
  cloudflare:apiToken:
    secure: AAABACByNobnYI4YhGFqM3DS0tG72wzDHXBdRhJosY6kkJyLeV9Xukp8kGK0DA/VUrXqBHyR3camz0YBu4jSN3748qmLUyR7
