config:
  # Azure
  azure-native:location: westus
  azure-native:subscriptionId: 331269d5-143f-4246-b389-9c1f41bb5882
  # Postgres
  aamini-infra:postgres:
    skuName: Standard_B1ms
    skuTier: Burstable
    storageSizeGb: 32
    backupRetentionDays: 7
    geoRedundantBackup: Disabled
