config:
  # Azure
  azure-native:location: westus
  azure-native:subscriptionId: 331269d5-143f-4246-b389-9c1f41bb5882

  aamini-platform:resourceGroupName: rg-aamini-staging
  aamini-platform:nodeResourceGroupName: rg-aamini-nodes-staging

  aamini-platform:githubOrganizationName: aamini-stack
  aamini-platform:githubRepositoryName: projects

  aamini-platform:aksSpecs:
    maxSurge: '1'
    nodeCount: 1
    vmSize: Standard_DS2_v2

  aamini-platform:dbSpecs:
    backupRetentionDays: 7
    geoRedundantBackup: Disabled
    skuName: Standard_B1ms
    skuTier: Burstable
    storageSizeGb: 32

  aamini-platform:cloudflareApiToken:
    secure: AAABAEvj2lg+c2ye1m8O526jNsrzDzGorUcOyCCegb0Vo0Hg4iZ66sTO4HiO6SG6/86Gj9/qBaKa9EEgdB69+sq/utOL3Ynb
  aamini-platform:dbPassword:
    secure: AAABAAsNrHBK4mJ7UgWepfAMWPyUBOS6Bt3qzegJEtFU27XJlFGrP/EwIEV3ZNjUAywbr6mkm3z1fvM/Odwxqw==
  aamini-platform:githubApiToken:
    secure: AAABAIWRulUv/SLLZ6fg/UVl9iBDRyLSwGzW0DqT7IadEZh5/TwgQJxpRaUeN2WDaMLGgIDrXL/QXCSPCOI5S6rD7zbWJGfx03/SzL8HRR3css6seohnG1Pb0IVViGV9QkXE6//J158b8jt9uEpXfYQkGr0TQhG4nakOdEY=
