/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DeploymentsRouteImport } from './routes/deployments'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectProjectIdRouteImport } from './routes/project.$projectId'
import { Route as ProjectProjectIdIndexRouteImport } from './routes/project.$projectId.index'
import { Route as ProjectProjectIdDeploymentsRouteImport } from './routes/project.$projectId.deployments'
import { Route as ProjectProjectIdDeploymentsDeploymentIdRouteImport } from './routes/project.$projectId.deployments.$deploymentId'
import { Route as ApiOauthGithubCallbackRouteImport } from './routes/api/oauth/github/callback'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentsRoute = DeploymentsRouteImport.update({
  id: '/deployments',
  path: '/deployments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdRoute = ProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdIndexRoute = ProjectProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const ProjectProjectIdDeploymentsRoute =
  ProjectProjectIdDeploymentsRouteImport.update({
    id: '/deployments',
    path: '/deployments',
    getParentRoute: () => ProjectProjectIdRoute,
  } as any)
const ProjectProjectIdDeploymentsDeploymentIdRoute =
  ProjectProjectIdDeploymentsDeploymentIdRouteImport.update({
    id: '/$deploymentId',
    path: '/$deploymentId',
    getParentRoute: () => ProjectProjectIdDeploymentsRoute,
  } as any)
const ApiOauthGithubCallbackRoute = ApiOauthGithubCallbackRouteImport.update({
  id: '/api/oauth/github/callback',
  path: '/api/oauth/github/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/deployments': typeof DeploymentsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/project/$projectId': typeof ProjectProjectIdRouteWithChildren
  '/project/$projectId/deployments': typeof ProjectProjectIdDeploymentsRouteWithChildren
  '/project/$projectId/': typeof ProjectProjectIdIndexRoute
  '/api/oauth/github/callback': typeof ApiOauthGithubCallbackRoute
  '/project/$projectId/deployments/$deploymentId': typeof ProjectProjectIdDeploymentsDeploymentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deployments': typeof DeploymentsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/project/$projectId/deployments': typeof ProjectProjectIdDeploymentsRouteWithChildren
  '/project/$projectId': typeof ProjectProjectIdIndexRoute
  '/api/oauth/github/callback': typeof ApiOauthGithubCallbackRoute
  '/project/$projectId/deployments/$deploymentId': typeof ProjectProjectIdDeploymentsDeploymentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/deployments': typeof DeploymentsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/project/$projectId': typeof ProjectProjectIdRouteWithChildren
  '/project/$projectId/deployments': typeof ProjectProjectIdDeploymentsRouteWithChildren
  '/project/$projectId/': typeof ProjectProjectIdIndexRoute
  '/api/oauth/github/callback': typeof ApiOauthGithubCallbackRoute
  '/project/$projectId/deployments/$deploymentId': typeof ProjectProjectIdDeploymentsDeploymentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/deployments'
    | '/login'
    | '/settings'
    | '/project/$projectId'
    | '/project/$projectId/deployments'
    | '/project/$projectId/'
    | '/api/oauth/github/callback'
    | '/project/$projectId/deployments/$deploymentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/deployments'
    | '/login'
    | '/settings'
    | '/project/$projectId/deployments'
    | '/project/$projectId'
    | '/api/oauth/github/callback'
    | '/project/$projectId/deployments/$deploymentId'
  id:
    | '__root__'
    | '/'
    | '/deployments'
    | '/login'
    | '/settings'
    | '/project/$projectId'
    | '/project/$projectId/deployments'
    | '/project/$projectId/'
    | '/api/oauth/github/callback'
    | '/project/$projectId/deployments/$deploymentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeploymentsRoute: typeof DeploymentsRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  ProjectProjectIdRoute: typeof ProjectProjectIdRouteWithChildren
  ApiOauthGithubCallbackRoute: typeof ApiOauthGithubCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployments': {
      id: '/deployments'
      path: '/deployments'
      fullPath: '/deployments'
      preLoaderRoute: typeof DeploymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId': {
      id: '/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId/': {
      id: '/project/$projectId/'
      path: '/'
      fullPath: '/project/$projectId/'
      preLoaderRoute: typeof ProjectProjectIdIndexRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/deployments': {
      id: '/project/$projectId/deployments'
      path: '/deployments'
      fullPath: '/project/$projectId/deployments'
      preLoaderRoute: typeof ProjectProjectIdDeploymentsRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/deployments/$deploymentId': {
      id: '/project/$projectId/deployments/$deploymentId'
      path: '/$deploymentId'
      fullPath: '/project/$projectId/deployments/$deploymentId'
      preLoaderRoute: typeof ProjectProjectIdDeploymentsDeploymentIdRouteImport
      parentRoute: typeof ProjectProjectIdDeploymentsRoute
    }
    '/api/oauth/github/callback': {
      id: '/api/oauth/github/callback'
      path: '/api/oauth/github/callback'
      fullPath: '/api/oauth/github/callback'
      preLoaderRoute: typeof ApiOauthGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProjectProjectIdDeploymentsRouteChildren {
  ProjectProjectIdDeploymentsDeploymentIdRoute: typeof ProjectProjectIdDeploymentsDeploymentIdRoute
}

const ProjectProjectIdDeploymentsRouteChildren: ProjectProjectIdDeploymentsRouteChildren =
  {
    ProjectProjectIdDeploymentsDeploymentIdRoute:
      ProjectProjectIdDeploymentsDeploymentIdRoute,
  }

const ProjectProjectIdDeploymentsRouteWithChildren =
  ProjectProjectIdDeploymentsRoute._addFileChildren(
    ProjectProjectIdDeploymentsRouteChildren,
  )

interface ProjectProjectIdRouteChildren {
  ProjectProjectIdDeploymentsRoute: typeof ProjectProjectIdDeploymentsRouteWithChildren
  ProjectProjectIdIndexRoute: typeof ProjectProjectIdIndexRoute
}

const ProjectProjectIdRouteChildren: ProjectProjectIdRouteChildren = {
  ProjectProjectIdDeploymentsRoute:
    ProjectProjectIdDeploymentsRouteWithChildren,
  ProjectProjectIdIndexRoute: ProjectProjectIdIndexRoute,
}

const ProjectProjectIdRouteWithChildren =
  ProjectProjectIdRoute._addFileChildren(ProjectProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeploymentsRoute: DeploymentsRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  ProjectProjectIdRoute: ProjectProjectIdRouteWithChildren,
  ApiOauthGithubCallbackRoute: ApiOauthGithubCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
