/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSendEmailRouteImport } from './routes/api/sendEmail'
import { Route as ApiAnalyticsRouteRouteImport } from './routes/api/analytics/$route'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendEmailRoute = ApiSendEmailRouteImport.update({
  id: '/api/sendEmail',
  path: '/api/sendEmail',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsRouteRoute = ApiAnalyticsRouteRouteImport.update({
  id: '/api/analytics/$route',
  path: '/api/analytics/$route',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/sendEmail': typeof ApiSendEmailRoute
  '/api/analytics/$route': typeof ApiAnalyticsRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/sendEmail': typeof ApiSendEmailRoute
  '/api/analytics/$route': typeof ApiAnalyticsRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/sendEmail': typeof ApiSendEmailRoute
  '/api/analytics/$route': typeof ApiAnalyticsRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/sendEmail' | '/api/analytics/$route'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/sendEmail' | '/api/analytics/$route'
  id: '__root__' | '/' | '/api/sendEmail' | '/api/analytics/$route'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiSendEmailRoute: typeof ApiSendEmailRoute
  ApiAnalyticsRouteRoute: typeof ApiAnalyticsRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sendEmail': {
      id: '/api/sendEmail'
      path: '/api/sendEmail'
      fullPath: '/api/sendEmail'
      preLoaderRoute: typeof ApiSendEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics/$route': {
      id: '/api/analytics/$route'
      path: '/api/analytics/$route'
      fullPath: '/api/analytics/$route'
      preLoaderRoute: typeof ApiAnalyticsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiSendEmailRoute: ApiSendEmailRoute,
  ApiAnalyticsRouteRoute: ApiAnalyticsRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
