---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: portfolio-secrets
  namespace: portfolio
spec:
  encryptedData:
    MAILGUN_API_KEY: AgCNJDtJGAeohlo9ui+wnMnScezxXbFt84nxX4pyDbdDtZjIdiuCMhN9EDOUhRdv9IxuvUwqazZx/9vOZjZCCfm+YgBqeVBJrnPlA2Klxion8qjUmWkj1UAcMqqyG1ZW5f7zSbPMGxzish6PfmlDZMWQFuPK+/GTY3i+41dnTASJpyMV4GmK76yRotEH0TsKuM39nkegPb8dVRbjc3EWBJKCYsh68Ex4LbI8tTvboiTTGJExqvecyHhbHLUK7lXrVBojt0Ef9RcsvDIPa4xSdR801rc+l372oQ+PLAWVrPnkMjEqg3MFLiBel4q5Q08ncz4hrHdkwD4Rnr+g5u97kfySXKqS/9N+IIx2mmp3i2vY9sP2hbzCtJNzY4khQDVhxnm0GILgfq+pjiIAm4QRVYP9AUl4zXHTe64OYW1UnXqjqmd1LIwgQzNMI23jpHcCpidJaz5DH7uQE9zRGtGGH0YpA1+dP3Sw1NpKPz0dMnt/xo7hBdDafEEC8A4ujpYHl05NRcrOYGsHC3BHguhddVHcTHLDMukgMzpe9HL7rHgWrv3JpAJTuDimHalVjwiyq7NR2AqtBJCESqu0XHNw0snMZ+14rSnrkPREon0bzHOITylHmEk6FEfnDumLyYD6bVPnrkrcz6+RTppT0kKxEzINUGOggYLbWB/7rS8NE2Q1IhMTdEVj5MedVWjlfq9YM9tVVcwCaHcJa2NclA==
    MAILGUN_DOMAIN: AgBa2KaL0FvsSW/0qpal0DGAJ5sbSoRumzwFASXgjYFe6g8Nb8am9dr/lOnClX3aV2OWpIwvQjNfSWyU+d73sT6joLw4AaCojddANl9eBOLlqLbg7uDqrFcmxeCwWjgRm4yi5wsU6aE+mp80gE2SpteKZp6U3hjXomVRDqqokln2hwSbtK0WrLSF8Yz1rEf6ba43K5ZtaCYQ7IDFCw1sy4Y2+GouqrloRHHJuJQ2j/DzUzGF+2aZ0tN3RIhxMOfZjuHquiCjGVkn+TEYK1xj41byh8FNC5JMC7H0KHCmv8pwIMOcYMohtLreOAa/p1I+g42SbAof5/KxhzewuPuZv/ORMbUSpW6NmnuH0I930c8IZaQMyKkMXiRcBfokBwk3OrAxURcoGzMGShHM+tZ/FZzPiVV1UgsiQDDauVTXsjJStwmESziw7SrdjBop1VsfYVmqtTGvQVcIJNm8Ub9g/pY9R91nAslMGkZnDfxVaODJAUXctKgmgQpDG/ZCkwpHNJ1CKUJoIY0OB1nfL+rzXcVN/M2diK+/2QWaPgj56CxObubMG7RGWZplSyfEZrl3HtgQZ3aR7oh0sfU0Jj5sN4v87cj9vMoNruUSBwa11bNet3bK+zoZoNgTLG6b2rJHEyCznKokQO55Wugp/ChfJbbqII6+wiP3rJ/GdClWOhBcfF4bxCdqUOQxz3g0uNcXbFTPlzCSqNbfc/7Oig==
  template:
    metadata:
      name: portfolio-secrets
      namespace: portfolio
