apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: networking
spec:
  encryptedData:
    api-token: REPLACE_WITH_KUBESEAL_OUTPUT
  template:
    metadata:
      name: cloudflare-api-token
      namespace: networking
    type: Opaque
