FROM mcr.microsoft.com/playwright:v1.57.0-noble

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
ENV COREPACK_ENABLE_DOWNLOAD_PROMPT=0
RUN corepack enable pnpm

WORKDIR /app
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY ./packages/ ./packages/
COPY ./apps/pc-tune-ups/package.json package.json
RUN  --mount=type=cache,id=pnpm,target=/pnpm/store pnpm i
WORKDIR /app/apps/pc-tune-ups
COPY ./apps/pc-tune-ups/ .
ENTRYPOINT ["pnpm", "playwright", "test"]
