config:
  landing-zone:accountId: "135133927765"
  landing-zone:environment: staging
  landing-zone:managementAccountId: "302481198387"
  landing-zone:assumeRoleName: OrganizationAccountAccessRole
  landing-zone:region: us-east-1
  landing-zone:budgetLimitUsd: "150"
  landing-zone:billingAlertEmail: platform-alerts@example.com
  landing-zone:ciCdPrincipalArn: arn:aws:iam::302481198387:role/PulumiOperatorRole
