image:
  repository: ghcr.io/aamini-stack/app
  tag: latest
  pullPolicy: IfNotPresent
app:
  name: app-release
  namespace: app-release
deployRevision: ''
host: ''
rootHost: ''
service:
  port: 80
  targetPort: 3000
resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 512Mi
    cpu: 250m
envFromSecret: ''
