name: dota-visualizer
namespace: dota-visualizer
image:
  repository: 302481198387.dkr.ecr.us-east-1.amazonaws.com/dota-visualizer
  policy: dota-visualizer
stable:
  host: dota-visualizer.ariaamini.com
preview:
  enabled: true
