name: imdbgraph
namespace: imdbgraph
image:
  repository: 302481198387.dkr.ecr.us-east-1.amazonaws.com/imdbgraph
  policy: imdbgraph
stable:
  host: imdbgraph.ariaamini.com
  envFromSecret: imdbgraph-secrets
preview:
  enabled: true
