name: imdbgraph
namespace: imdbgraph
image:
  repository: aaministack.azurecr.io/imdbgraph
  policy: imdbgraph
stable:
  host: imdbgraph.ariaamini.com
  envFromSecret: imdbgraph-secrets
preview:
  enabled: true
