name: pc-tune-ups
namespace: pc-tune-ups
image:
  repository: 302481198387.dkr.ecr.us-east-1.amazonaws.com/pc-tune-ups
  policy: pc-tune-ups
stable:
  host: pc-tune-ups.ariaamini.com
preview:
  enabled: true
