name: portfolio
namespace: portfolio
image:
  repository: aaministack.azurecr.io/portfolio
  policy: portfolio
stable:
  host: portfolio.ariaamini.com
  rootHost: ariaamini.com
  envFromSecret: portfolio-secrets
preview:
  enabled: true
