---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: flux-receiver-auth
  namespace: flux-system
spec:
  encryptedData:
    token: AgAJ9WkwaJyOA7fXf2cOAZ1zXgeCPBOE+ApgwY7DYNQ/EoDD1SJVTtQgMgW/W/NGKpsWtmxAA/gBj0zBxpWoRiPJgJHfRRyJNfmGabrKTMQ96uI1fwHa/hm1Z5C+9WChGc14eSO9Wf2zfHBAMTfUaeuPO3icROPIjDB/4i3ttBOsxav5rd7lipG4Sqj/MVRGe3oBZfX4oKdq8IeK7wvyr1XUQpsS3HdGupRbNikGHYsVsf8BnXPihDsLHEai2uOmJ7ZRqOvJamGW0K0fAijJOvohtnQhQrt+A+bZ0I2p9VM3FId5xRnINYeQjCTYjMkMcjftuE+TQop9//mNKrV42Y9deCWzpF+aDZTwWW77W5kcoaBU3wFN2Llp3zNcDCejNCS4EFTogoaK7ItqNXnEqRRKNiAFS0M+Xn+ps7Nzs/Vmofl/XUtDmCLOiDYcM7LHahmJkSJ3PLtVAOwlSkcCfklMBx60MGPiAvkGpWrk00td6TsAwCWL4aV9RG4r9oY0RC8Aag9XMeV27j0ffs4G39FO/jxxllApUmuHYB4PjTAGACEKn/GNSsk0Xn6zOO9fFpuG0cb2q3gpaHrDyc3OIZUcZ73SZiQfscP1d9JH3pW5pxkxBKA6wFgRZOqwoHNKhVHIqK1o+HYnRfjolkEPJiQ9+YaEPK3ILYUJ4AwLKqmxlMkNXk30QSGUlVv9RpUV1rAdQyh3VWlcOWy2FhpYZz9VYjd4ZXJ8WDloYSHQmi62/qt8ycTwLVqEqRx2lQOVHSP1DSpXvM1gfreSEW6GRDaV
  template:
    metadata:
      name: flux-receiver-auth
      namespace: flux-system
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-dispatch-auth
  namespace: flux-system
spec:
  encryptedData:
    token: AgByI244UOBGdH+f5Upoh4X8bQE0jMJK+Hb33OwtK4HkRPuzU+kKjkab2BXWYum2kvYB5iKrkxa9AnZ6V2fv7WoFGSsAV67CgW1UQatw+Q4yGDmUb/pAPCE39JYnQWZeOv2P24cAo0I26NnC607f8bgUa/Mg9JlLkv/nVx1NvzPiVuD1ZjD0CVya+OF2t6HHz4E3u6TBr6qfBI6hvajxc7P+HuDCFZa79Fk8IABmKeBMTybRSKuaIpDfPMo2MIDNXh6v+6L7ZRrqUYqwOhpUHi80yR5u4Ej8J3wZ7oFb6Z6lABr4w52TgA1erisZKl72WVvEwDE/QoWCQNG+2t4nIVRBTop84oEkHweAExOoIfjA7T33Cb/l34kGWRBsy5/LcGGP5w0rJk/ccyXQCPor6Ut6cYmpzanUCqe18QfRNFvm9L7Zv1DhukLlfKL17Ce+vIgOHVujP6EM4JCHqMLxTuKWQJ0zdW3qJ2l+zTDeMXJu94uRk4vJz7+qu2k63OdEWgxeghwkwKIEmQprGXbjP5fV5uNxlZPPe6IsAwWC2LjGB4rfAoORmbv/Plz/E8ifyogMwVK4n3EAWeHzVQK2qs0wc35rvwRTqpq69jmbr1laVFijwwZbERTpRoZ+WdVbTXUYNBIBYV9qCpxGlVcPU9WQNJRNczM7mFD5s0AH22eG9KGIFAUY7UaoPND8r7p8MAutFKZ9gaFUiomBKn+cxM3sq6O8uE03gPPHiApJp2CWnfDtl5/ZdwAlUqR0hzcvkonJfH5jIG9wyzEFRbHFGU0gIb7JI2FUkoXmAkiAIbKFF04hTI39y5xo//2cl90=
  template:
    metadata:
      name: github-dispatch-auth
      namespace: flux-system
