---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: flux-receiver-auth
  namespace: flux-system
spec:
  encryptedData:
    token: AgBjeopfGdAG23jXJVY5vsmBTsVlifVws7P9RgfYePTLe/+15B36+GBJw9HaTuCDKFesKfigmO6yKaDL1Bx/uOP+rej9SZZtwkIBIHxgAhyr5fW9d+FKbWkM9Xz7/YRR7Tc6e1ysldWQAbUiBaR9JXSif6OKmT04fYQUm5cSSfq3dP1M177svDryxtld4IWwDPoeZ9IV1B5nwX42Rlwk6HsmVBUuK3PYFxGMR+9QudCjCpIgd9fi6C2todbyvExUYJQO++GwnA6uYwBTAwysR/Yr1enMkSU+eNV61OUcWJB/vrfP/fuNfC/KPxnX66hKLnd6fLiwsqclP7R/YMTAx4dSTbQ7PFmRIWIU/uQOegwMbz7dulwBGsIvmuydG14ULKcENMjHrEaMGuYYjS2E4sAKHZhyJUFdwq0BjV+VTOczCRQhJ/22J7N1lFKxLIYWPa5GDt1gCilZuGcaGU6AJWp8ycDnCtxBKA5C3M36D3T86zslOZOBIBXPz5kUQGhi7ArjvLfS71nw/yL8WWO+trKgav0716WOlaqLB2RWhfnTqFDqnHzp+Fs4XxjeEio3UPX9WHCtfOGqx2Z6MrXgAiGl+rcef7JwT+WzXaEJTjYwcOj6V5+Nhmx541wYQyq/OJ3PK3f2O0alGdyu7sbQ2a/G4PUCzl0QR+8NBShOJD5jfq/BQbbBRxnZ3AmAn8dlDaO65SbDKBClP3VwtIaPy9fyKvDTKGDqiFASlCA1QjmXzsOqp5adIirF0klV70evQzbkEOhZo4ij+t2QfMTVVQmo
  template:
    metadata:
      name: flux-receiver-auth
      namespace: flux-system
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-dispatch-auth
  namespace: flux-system
spec:
  encryptedData:
    token: AgByI244UOBGdH+f5Upoh4X8bQE0jMJK+Hb33OwtK4HkRPuzU+kKjkab2BXWYum2kvYB5iKrkxa9AnZ6V2fv7WoFGSsAV67CgW1UQatw+Q4yGDmUb/pAPCE39JYnQWZeOv2P24cAo0I26NnC607f8bgUa/Mg9JlLkv/nVx1NvzPiVuD1ZjD0CVya+OF2t6HHz4E3u6TBr6qfBI6hvajxc7P+HuDCFZa79Fk8IABmKeBMTybRSKuaIpDfPMo2MIDNXh6v+6L7ZRrqUYqwOhpUHi80yR5u4Ej8J3wZ7oFb6Z6lABr4w52TgA1erisZKl72WVvEwDE/QoWCQNG+2t4nIVRBTop84oEkHweAExOoIfjA7T33Cb/l34kGWRBsy5/LcGGP5w0rJk/ccyXQCPor6Ut6cYmpzanUCqe18QfRNFvm9L7Zv1DhukLlfKL17Ce+vIgOHVujP6EM4JCHqMLxTuKWQJ0zdW3qJ2l+zTDeMXJu94uRk4vJz7+qu2k63OdEWgxeghwkwKIEmQprGXbjP5fV5uNxlZPPe6IsAwWC2LjGB4rfAoORmbv/Plz/E8ifyogMwVK4n3EAWeHzVQK2qs0wc35rvwRTqpq69jmbr1laVFijwwZbERTpRoZ+WdVbTXUYNBIBYV9qCpxGlVcPU9WQNJRNczM7mFD5s0AH22eG9KGIFAUY7UaoPND8r7p8MAutFKZ9gaFUiomBKn+cxM3sq6O8uE03gPPHiApJp2CWnfDtl5/ZdwAlUqR0hzcvkonJfH5jIG9wyzEFRbHFGU0gIb7JI2FUkoXmAkiAIbKFF04hTI39y5xo//2cl90=
  template:
    metadata:
      name: github-dispatch-auth
      namespace: flux-system
