/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as MatchActivityRouteImport } from './routes/match-activity'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BetaRouteImport } from './routes/beta'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsumerIndexRouteImport } from './routes/consumer/index'
import { Route as AgentIndexRouteImport } from './routes/agent/index'
import { Route as ConsumerResultsRouteImport } from './routes/consumer/results'
import { Route as ConsumerQuizRouteImport } from './routes/consumer/quiz'
import { Route as AgentQuizRouteImport } from './routes/agent/quiz'
import { Route as AgentProfileRouteImport } from './routes/agent/profile'
import { Route as ApiIngestSplatRouteImport } from './routes/api/ingest/$'
import { Route as ApiBetaAuthRouteImport } from './routes/api/beta/auth'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiIngestStaticSplatRouteImport } from './routes/api/ingest/static/$'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchActivityRoute = MatchActivityRouteImport.update({
  id: '/match-activity',
  path: '/match-activity',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BetaRoute = BetaRouteImport.update({
  id: '/beta',
  path: '/beta',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumerIndexRoute = ConsumerIndexRouteImport.update({
  id: '/consumer/',
  path: '/consumer/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentIndexRoute = AgentIndexRouteImport.update({
  id: '/agent/',
  path: '/agent/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumerResultsRoute = ConsumerResultsRouteImport.update({
  id: '/consumer/results',
  path: '/consumer/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumerQuizRoute = ConsumerQuizRouteImport.update({
  id: '/consumer/quiz',
  path: '/consumer/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentQuizRoute = AgentQuizRouteImport.update({
  id: '/agent/quiz',
  path: '/agent/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentProfileRoute = AgentProfileRouteImport.update({
  id: '/agent/profile',
  path: '/agent/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestSplatRoute = ApiIngestSplatRouteImport.update({
  id: '/api/ingest/$',
  path: '/api/ingest/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBetaAuthRoute = ApiBetaAuthRouteImport.update({
  id: '/api/beta/auth',
  path: '/api/beta/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestStaticSplatRoute = ApiIngestStaticSplatRouteImport.update({
  id: '/api/ingest/static/$',
  path: '/api/ingest/static/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/beta': typeof BetaRoute
  '/login': typeof LoginRoute
  '/match-activity': typeof MatchActivityRoute
  '/signup': typeof SignupRoute
  '/agent/profile': typeof AgentProfileRoute
  '/agent/quiz': typeof AgentQuizRoute
  '/consumer/quiz': typeof ConsumerQuizRoute
  '/consumer/results': typeof ConsumerResultsRoute
  '/agent/': typeof AgentIndexRoute
  '/consumer/': typeof ConsumerIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/beta/auth': typeof ApiBetaAuthRoute
  '/api/ingest/$': typeof ApiIngestSplatRoute
  '/api/ingest/static/$': typeof ApiIngestStaticSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/beta': typeof BetaRoute
  '/login': typeof LoginRoute
  '/match-activity': typeof MatchActivityRoute
  '/signup': typeof SignupRoute
  '/agent/profile': typeof AgentProfileRoute
  '/agent/quiz': typeof AgentQuizRoute
  '/consumer/quiz': typeof ConsumerQuizRoute
  '/consumer/results': typeof ConsumerResultsRoute
  '/agent': typeof AgentIndexRoute
  '/consumer': typeof ConsumerIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/beta/auth': typeof ApiBetaAuthRoute
  '/api/ingest/$': typeof ApiIngestSplatRoute
  '/api/ingest/static/$': typeof ApiIngestStaticSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/beta': typeof BetaRoute
  '/login': typeof LoginRoute
  '/match-activity': typeof MatchActivityRoute
  '/signup': typeof SignupRoute
  '/agent/profile': typeof AgentProfileRoute
  '/agent/quiz': typeof AgentQuizRoute
  '/consumer/quiz': typeof ConsumerQuizRoute
  '/consumer/results': typeof ConsumerResultsRoute
  '/agent/': typeof AgentIndexRoute
  '/consumer/': typeof ConsumerIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/beta/auth': typeof ApiBetaAuthRoute
  '/api/ingest/$': typeof ApiIngestSplatRoute
  '/api/ingest/static/$': typeof ApiIngestStaticSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/beta'
    | '/login'
    | '/match-activity'
    | '/signup'
    | '/agent/profile'
    | '/agent/quiz'
    | '/consumer/quiz'
    | '/consumer/results'
    | '/agent/'
    | '/consumer/'
    | '/api/auth/$'
    | '/api/beta/auth'
    | '/api/ingest/$'
    | '/api/ingest/static/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/beta'
    | '/login'
    | '/match-activity'
    | '/signup'
    | '/agent/profile'
    | '/agent/quiz'
    | '/consumer/quiz'
    | '/consumer/results'
    | '/agent'
    | '/consumer'
    | '/api/auth/$'
    | '/api/beta/auth'
    | '/api/ingest/$'
    | '/api/ingest/static/$'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/beta'
    | '/login'
    | '/match-activity'
    | '/signup'
    | '/agent/profile'
    | '/agent/quiz'
    | '/consumer/quiz'
    | '/consumer/results'
    | '/agent/'
    | '/consumer/'
    | '/api/auth/$'
    | '/api/beta/auth'
    | '/api/ingest/$'
    | '/api/ingest/static/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  BetaRoute: typeof BetaRoute
  LoginRoute: typeof LoginRoute
  MatchActivityRoute: typeof MatchActivityRoute
  SignupRoute: typeof SignupRoute
  AgentProfileRoute: typeof AgentProfileRoute
  AgentQuizRoute: typeof AgentQuizRoute
  ConsumerQuizRoute: typeof ConsumerQuizRoute
  ConsumerResultsRoute: typeof ConsumerResultsRoute
  AgentIndexRoute: typeof AgentIndexRoute
  ConsumerIndexRoute: typeof ConsumerIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBetaAuthRoute: typeof ApiBetaAuthRoute
  ApiIngestSplatRoute: typeof ApiIngestSplatRoute
  ApiIngestStaticSplatRoute: typeof ApiIngestStaticSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match-activity': {
      id: '/match-activity'
      path: '/match-activity'
      fullPath: '/match-activity'
      preLoaderRoute: typeof MatchActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beta': {
      id: '/beta'
      path: '/beta'
      fullPath: '/beta'
      preLoaderRoute: typeof BetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumer/': {
      id: '/consumer/'
      path: '/consumer'
      fullPath: '/consumer/'
      preLoaderRoute: typeof ConsumerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/': {
      id: '/agent/'
      path: '/agent'
      fullPath: '/agent/'
      preLoaderRoute: typeof AgentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumer/results': {
      id: '/consumer/results'
      path: '/consumer/results'
      fullPath: '/consumer/results'
      preLoaderRoute: typeof ConsumerResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumer/quiz': {
      id: '/consumer/quiz'
      path: '/consumer/quiz'
      fullPath: '/consumer/quiz'
      preLoaderRoute: typeof ConsumerQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/quiz': {
      id: '/agent/quiz'
      path: '/agent/quiz'
      fullPath: '/agent/quiz'
      preLoaderRoute: typeof AgentQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/profile': {
      id: '/agent/profile'
      path: '/agent/profile'
      fullPath: '/agent/profile'
      preLoaderRoute: typeof AgentProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest/$': {
      id: '/api/ingest/$'
      path: '/api/ingest/$'
      fullPath: '/api/ingest/$'
      preLoaderRoute: typeof ApiIngestSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/beta/auth': {
      id: '/api/beta/auth'
      path: '/api/beta/auth'
      fullPath: '/api/beta/auth'
      preLoaderRoute: typeof ApiBetaAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest/static/$': {
      id: '/api/ingest/static/$'
      path: '/api/ingest/static/$'
      fullPath: '/api/ingest/static/$'
      preLoaderRoute: typeof ApiIngestStaticSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  BetaRoute: BetaRoute,
  LoginRoute: LoginRoute,
  MatchActivityRoute: MatchActivityRoute,
  SignupRoute: SignupRoute,
  AgentProfileRoute: AgentProfileRoute,
  AgentQuizRoute: AgentQuizRoute,
  ConsumerQuizRoute: ConsumerQuizRoute,
  ConsumerResultsRoute: ConsumerResultsRoute,
  AgentIndexRoute: AgentIndexRoute,
  ConsumerIndexRoute: ConsumerIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBetaAuthRoute: ApiBetaAuthRoute,
  ApiIngestSplatRoute: ApiIngestSplatRoute,
  ApiIngestStaticSplatRoute: ApiIngestStaticSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
