/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShowcaseRouteImport } from './routes/showcase'
import { Route as MatchActivityRouteImport } from './routes/match-activity'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BetaRouteImport } from './routes/beta'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SellerIndexRouteImport } from './routes/seller/index'
import { Route as ConsumerIndexRouteImport } from './routes/consumer/index'
import { Route as BuyerIndexRouteImport } from './routes/buyer/index'
import { Route as AgentIndexRouteImport } from './routes/agent/index'
import { Route as ThemesThemeNameRouteImport } from './routes/themes/$themeName'
import { Route as SellerUnlockRouteImport } from './routes/seller/unlock'
import { Route as SellerSummaryRouteImport } from './routes/seller/summary'
import { Route as SellerResultsRouteImport } from './routes/seller/results'
import { Route as SellerQuizRouteImport } from './routes/seller/quiz'
import { Route as SellerIntroRouteImport } from './routes/seller/intro'
import { Route as SellerEmailRouteImport } from './routes/seller/email'
import { Route as SellerDetailsRouteImport } from './routes/seller/details'
import { Route as SellerChatRouteImport } from './routes/seller/chat'
import { Route as ConsumerResultsRouteImport } from './routes/consumer/results'
import { Route as ConsumerQuizRouteImport } from './routes/consumer/quiz'
import { Route as ConsumerPrioritiesRouteImport } from './routes/consumer/priorities'
import { Route as BuyerUnlockRouteImport } from './routes/buyer/unlock'
import { Route as BuyerSummaryRouteImport } from './routes/buyer/summary'
import { Route as BuyerResultsRouteImport } from './routes/buyer/results'
import { Route as BuyerQuizRouteImport } from './routes/buyer/quiz'
import { Route as BuyerIntroRouteImport } from './routes/buyer/intro'
import { Route as BuyerEmailRouteImport } from './routes/buyer/email'
import { Route as BuyerDetailsRouteImport } from './routes/buyer/details'
import { Route as BuyerChatRouteImport } from './routes/buyer/chat'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiAgentMatchesRouteImport } from './routes/api/agent-matches'
import { Route as AgentSubscribeRouteImport } from './routes/agent/subscribe'
import { Route as AgentQuizRouteImport } from './routes/agent/quiz'
import { Route as AgentProfileRouteImport } from './routes/agent/profile'
import { Route as AgentPrioritiesRouteImport } from './routes/agent/priorities'
import { Route as AgentPeacePactRouteImport } from './routes/agent/peace-pact'
import { Route as AgentDeepDiveRouteImport } from './routes/agent/deep-dive'
import { Route as AgentComplianceRouteImport } from './routes/agent/compliance'
import { Route as AgentChatRouteImport } from './routes/agent/chat'
import { Route as ApiIngestSplatRouteImport } from './routes/api/ingest/$'
import { Route as ApiBetaAuthRouteImport } from './routes/api/beta/auth'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiIngestStaticSplatRouteImport } from './routes/api/ingest/static/$'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseRoute = ShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchActivityRoute = MatchActivityRouteImport.update({
  id: '/match-activity',
  path: '/match-activity',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BetaRoute = BetaRouteImport.update({
  id: '/beta',
  path: '/beta',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerIndexRoute = SellerIndexRouteImport.update({
  id: '/seller/',
  path: '/seller/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumerIndexRoute = ConsumerIndexRouteImport.update({
  id: '/consumer/',
  path: '/consumer/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerIndexRoute = BuyerIndexRouteImport.update({
  id: '/buyer/',
  path: '/buyer/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentIndexRoute = AgentIndexRouteImport.update({
  id: '/agent/',
  path: '/agent/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemesThemeNameRoute = ThemesThemeNameRouteImport.update({
  id: '/themes/$themeName',
  path: '/themes/$themeName',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerUnlockRoute = SellerUnlockRouteImport.update({
  id: '/seller/unlock',
  path: '/seller/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerSummaryRoute = SellerSummaryRouteImport.update({
  id: '/seller/summary',
  path: '/seller/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerResultsRoute = SellerResultsRouteImport.update({
  id: '/seller/results',
  path: '/seller/results',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerQuizRoute = SellerQuizRouteImport.update({
  id: '/seller/quiz',
  path: '/seller/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerIntroRoute = SellerIntroRouteImport.update({
  id: '/seller/intro',
  path: '/seller/intro',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerEmailRoute = SellerEmailRouteImport.update({
  id: '/seller/email',
  path: '/seller/email',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerDetailsRoute = SellerDetailsRouteImport.update({
  id: '/seller/details',
  path: '/seller/details',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerChatRoute = SellerChatRouteImport.update({
  id: '/seller/chat',
  path: '/seller/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumerResultsRoute = ConsumerResultsRouteImport.update({
  id: '/consumer/results',
  path: '/consumer/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumerQuizRoute = ConsumerQuizRouteImport.update({
  id: '/consumer/quiz',
  path: '/consumer/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumerPrioritiesRoute = ConsumerPrioritiesRouteImport.update({
  id: '/consumer/priorities',
  path: '/consumer/priorities',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerUnlockRoute = BuyerUnlockRouteImport.update({
  id: '/buyer/unlock',
  path: '/buyer/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerSummaryRoute = BuyerSummaryRouteImport.update({
  id: '/buyer/summary',
  path: '/buyer/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerResultsRoute = BuyerResultsRouteImport.update({
  id: '/buyer/results',
  path: '/buyer/results',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerQuizRoute = BuyerQuizRouteImport.update({
  id: '/buyer/quiz',
  path: '/buyer/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerIntroRoute = BuyerIntroRouteImport.update({
  id: '/buyer/intro',
  path: '/buyer/intro',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerEmailRoute = BuyerEmailRouteImport.update({
  id: '/buyer/email',
  path: '/buyer/email',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerDetailsRoute = BuyerDetailsRouteImport.update({
  id: '/buyer/details',
  path: '/buyer/details',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerChatRoute = BuyerChatRouteImport.update({
  id: '/buyer/chat',
  path: '/buyer/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentMatchesRoute = ApiAgentMatchesRouteImport.update({
  id: '/api/agent-matches',
  path: '/api/agent-matches',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentSubscribeRoute = AgentSubscribeRouteImport.update({
  id: '/agent/subscribe',
  path: '/agent/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentQuizRoute = AgentQuizRouteImport.update({
  id: '/agent/quiz',
  path: '/agent/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentProfileRoute = AgentProfileRouteImport.update({
  id: '/agent/profile',
  path: '/agent/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentPrioritiesRoute = AgentPrioritiesRouteImport.update({
  id: '/agent/priorities',
  path: '/agent/priorities',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentPeacePactRoute = AgentPeacePactRouteImport.update({
  id: '/agent/peace-pact',
  path: '/agent/peace-pact',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentDeepDiveRoute = AgentDeepDiveRouteImport.update({
  id: '/agent/deep-dive',
  path: '/agent/deep-dive',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentComplianceRoute = AgentComplianceRouteImport.update({
  id: '/agent/compliance',
  path: '/agent/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentChatRoute = AgentChatRouteImport.update({
  id: '/agent/chat',
  path: '/agent/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestSplatRoute = ApiIngestSplatRouteImport.update({
  id: '/api/ingest/$',
  path: '/api/ingest/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBetaAuthRoute = ApiBetaAuthRouteImport.update({
  id: '/api/beta/auth',
  path: '/api/beta/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestStaticSplatRoute = ApiIngestStaticSplatRouteImport.update({
  id: '/api/ingest/static/$',
  path: '/api/ingest/static/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/beta': typeof BetaRoute
  '/login': typeof LoginRoute
  '/match-activity': typeof MatchActivityRoute
  '/showcase': typeof ShowcaseRoute
  '/signup': typeof SignupRoute
  '/agent/chat': typeof AgentChatRoute
  '/agent/compliance': typeof AgentComplianceRoute
  '/agent/deep-dive': typeof AgentDeepDiveRoute
  '/agent/peace-pact': typeof AgentPeacePactRoute
  '/agent/priorities': typeof AgentPrioritiesRoute
  '/agent/profile': typeof AgentProfileRoute
  '/agent/quiz': typeof AgentQuizRoute
  '/agent/subscribe': typeof AgentSubscribeRoute
  '/api/agent-matches': typeof ApiAgentMatchesRoute
  '/api/health': typeof ApiHealthRoute
  '/buyer/chat': typeof BuyerChatRoute
  '/buyer/details': typeof BuyerDetailsRoute
  '/buyer/email': typeof BuyerEmailRoute
  '/buyer/intro': typeof BuyerIntroRoute
  '/buyer/quiz': typeof BuyerQuizRoute
  '/buyer/results': typeof BuyerResultsRoute
  '/buyer/summary': typeof BuyerSummaryRoute
  '/buyer/unlock': typeof BuyerUnlockRoute
  '/consumer/priorities': typeof ConsumerPrioritiesRoute
  '/consumer/quiz': typeof ConsumerQuizRoute
  '/consumer/results': typeof ConsumerResultsRoute
  '/seller/chat': typeof SellerChatRoute
  '/seller/details': typeof SellerDetailsRoute
  '/seller/email': typeof SellerEmailRoute
  '/seller/intro': typeof SellerIntroRoute
  '/seller/quiz': typeof SellerQuizRoute
  '/seller/results': typeof SellerResultsRoute
  '/seller/summary': typeof SellerSummaryRoute
  '/seller/unlock': typeof SellerUnlockRoute
  '/themes/$themeName': typeof ThemesThemeNameRoute
  '/agent/': typeof AgentIndexRoute
  '/buyer/': typeof BuyerIndexRoute
  '/consumer/': typeof ConsumerIndexRoute
  '/seller/': typeof SellerIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/beta/auth': typeof ApiBetaAuthRoute
  '/api/ingest/$': typeof ApiIngestSplatRoute
  '/api/ingest/static/$': typeof ApiIngestStaticSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/beta': typeof BetaRoute
  '/login': typeof LoginRoute
  '/match-activity': typeof MatchActivityRoute
  '/showcase': typeof ShowcaseRoute
  '/signup': typeof SignupRoute
  '/agent/chat': typeof AgentChatRoute
  '/agent/compliance': typeof AgentComplianceRoute
  '/agent/deep-dive': typeof AgentDeepDiveRoute
  '/agent/peace-pact': typeof AgentPeacePactRoute
  '/agent/priorities': typeof AgentPrioritiesRoute
  '/agent/profile': typeof AgentProfileRoute
  '/agent/quiz': typeof AgentQuizRoute
  '/agent/subscribe': typeof AgentSubscribeRoute
  '/api/agent-matches': typeof ApiAgentMatchesRoute
  '/api/health': typeof ApiHealthRoute
  '/buyer/chat': typeof BuyerChatRoute
  '/buyer/details': typeof BuyerDetailsRoute
  '/buyer/email': typeof BuyerEmailRoute
  '/buyer/intro': typeof BuyerIntroRoute
  '/buyer/quiz': typeof BuyerQuizRoute
  '/buyer/results': typeof BuyerResultsRoute
  '/buyer/summary': typeof BuyerSummaryRoute
  '/buyer/unlock': typeof BuyerUnlockRoute
  '/consumer/priorities': typeof ConsumerPrioritiesRoute
  '/consumer/quiz': typeof ConsumerQuizRoute
  '/consumer/results': typeof ConsumerResultsRoute
  '/seller/chat': typeof SellerChatRoute
  '/seller/details': typeof SellerDetailsRoute
  '/seller/email': typeof SellerEmailRoute
  '/seller/intro': typeof SellerIntroRoute
  '/seller/quiz': typeof SellerQuizRoute
  '/seller/results': typeof SellerResultsRoute
  '/seller/summary': typeof SellerSummaryRoute
  '/seller/unlock': typeof SellerUnlockRoute
  '/themes/$themeName': typeof ThemesThemeNameRoute
  '/agent': typeof AgentIndexRoute
  '/buyer': typeof BuyerIndexRoute
  '/consumer': typeof ConsumerIndexRoute
  '/seller': typeof SellerIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/beta/auth': typeof ApiBetaAuthRoute
  '/api/ingest/$': typeof ApiIngestSplatRoute
  '/api/ingest/static/$': typeof ApiIngestStaticSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/beta': typeof BetaRoute
  '/login': typeof LoginRoute
  '/match-activity': typeof MatchActivityRoute
  '/showcase': typeof ShowcaseRoute
  '/signup': typeof SignupRoute
  '/agent/chat': typeof AgentChatRoute
  '/agent/compliance': typeof AgentComplianceRoute
  '/agent/deep-dive': typeof AgentDeepDiveRoute
  '/agent/peace-pact': typeof AgentPeacePactRoute
  '/agent/priorities': typeof AgentPrioritiesRoute
  '/agent/profile': typeof AgentProfileRoute
  '/agent/quiz': typeof AgentQuizRoute
  '/agent/subscribe': typeof AgentSubscribeRoute
  '/api/agent-matches': typeof ApiAgentMatchesRoute
  '/api/health': typeof ApiHealthRoute
  '/buyer/chat': typeof BuyerChatRoute
  '/buyer/details': typeof BuyerDetailsRoute
  '/buyer/email': typeof BuyerEmailRoute
  '/buyer/intro': typeof BuyerIntroRoute
  '/buyer/quiz': typeof BuyerQuizRoute
  '/buyer/results': typeof BuyerResultsRoute
  '/buyer/summary': typeof BuyerSummaryRoute
  '/buyer/unlock': typeof BuyerUnlockRoute
  '/consumer/priorities': typeof ConsumerPrioritiesRoute
  '/consumer/quiz': typeof ConsumerQuizRoute
  '/consumer/results': typeof ConsumerResultsRoute
  '/seller/chat': typeof SellerChatRoute
  '/seller/details': typeof SellerDetailsRoute
  '/seller/email': typeof SellerEmailRoute
  '/seller/intro': typeof SellerIntroRoute
  '/seller/quiz': typeof SellerQuizRoute
  '/seller/results': typeof SellerResultsRoute
  '/seller/summary': typeof SellerSummaryRoute
  '/seller/unlock': typeof SellerUnlockRoute
  '/themes/$themeName': typeof ThemesThemeNameRoute
  '/agent/': typeof AgentIndexRoute
  '/buyer/': typeof BuyerIndexRoute
  '/consumer/': typeof ConsumerIndexRoute
  '/seller/': typeof SellerIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/beta/auth': typeof ApiBetaAuthRoute
  '/api/ingest/$': typeof ApiIngestSplatRoute
  '/api/ingest/static/$': typeof ApiIngestStaticSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/beta'
    | '/login'
    | '/match-activity'
    | '/showcase'
    | '/signup'
    | '/agent/chat'
    | '/agent/compliance'
    | '/agent/deep-dive'
    | '/agent/peace-pact'
    | '/agent/priorities'
    | '/agent/profile'
    | '/agent/quiz'
    | '/agent/subscribe'
    | '/api/agent-matches'
    | '/api/health'
    | '/buyer/chat'
    | '/buyer/details'
    | '/buyer/email'
    | '/buyer/intro'
    | '/buyer/quiz'
    | '/buyer/results'
    | '/buyer/summary'
    | '/buyer/unlock'
    | '/consumer/priorities'
    | '/consumer/quiz'
    | '/consumer/results'
    | '/seller/chat'
    | '/seller/details'
    | '/seller/email'
    | '/seller/intro'
    | '/seller/quiz'
    | '/seller/results'
    | '/seller/summary'
    | '/seller/unlock'
    | '/themes/$themeName'
    | '/agent/'
    | '/buyer/'
    | '/consumer/'
    | '/seller/'
    | '/api/auth/$'
    | '/api/beta/auth'
    | '/api/ingest/$'
    | '/api/ingest/static/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/beta'
    | '/login'
    | '/match-activity'
    | '/showcase'
    | '/signup'
    | '/agent/chat'
    | '/agent/compliance'
    | '/agent/deep-dive'
    | '/agent/peace-pact'
    | '/agent/priorities'
    | '/agent/profile'
    | '/agent/quiz'
    | '/agent/subscribe'
    | '/api/agent-matches'
    | '/api/health'
    | '/buyer/chat'
    | '/buyer/details'
    | '/buyer/email'
    | '/buyer/intro'
    | '/buyer/quiz'
    | '/buyer/results'
    | '/buyer/summary'
    | '/buyer/unlock'
    | '/consumer/priorities'
    | '/consumer/quiz'
    | '/consumer/results'
    | '/seller/chat'
    | '/seller/details'
    | '/seller/email'
    | '/seller/intro'
    | '/seller/quiz'
    | '/seller/results'
    | '/seller/summary'
    | '/seller/unlock'
    | '/themes/$themeName'
    | '/agent'
    | '/buyer'
    | '/consumer'
    | '/seller'
    | '/api/auth/$'
    | '/api/beta/auth'
    | '/api/ingest/$'
    | '/api/ingest/static/$'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/beta'
    | '/login'
    | '/match-activity'
    | '/showcase'
    | '/signup'
    | '/agent/chat'
    | '/agent/compliance'
    | '/agent/deep-dive'
    | '/agent/peace-pact'
    | '/agent/priorities'
    | '/agent/profile'
    | '/agent/quiz'
    | '/agent/subscribe'
    | '/api/agent-matches'
    | '/api/health'
    | '/buyer/chat'
    | '/buyer/details'
    | '/buyer/email'
    | '/buyer/intro'
    | '/buyer/quiz'
    | '/buyer/results'
    | '/buyer/summary'
    | '/buyer/unlock'
    | '/consumer/priorities'
    | '/consumer/quiz'
    | '/consumer/results'
    | '/seller/chat'
    | '/seller/details'
    | '/seller/email'
    | '/seller/intro'
    | '/seller/quiz'
    | '/seller/results'
    | '/seller/summary'
    | '/seller/unlock'
    | '/themes/$themeName'
    | '/agent/'
    | '/buyer/'
    | '/consumer/'
    | '/seller/'
    | '/api/auth/$'
    | '/api/beta/auth'
    | '/api/ingest/$'
    | '/api/ingest/static/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  BetaRoute: typeof BetaRoute
  LoginRoute: typeof LoginRoute
  MatchActivityRoute: typeof MatchActivityRoute
  ShowcaseRoute: typeof ShowcaseRoute
  SignupRoute: typeof SignupRoute
  AgentChatRoute: typeof AgentChatRoute
  AgentComplianceRoute: typeof AgentComplianceRoute
  AgentDeepDiveRoute: typeof AgentDeepDiveRoute
  AgentPeacePactRoute: typeof AgentPeacePactRoute
  AgentPrioritiesRoute: typeof AgentPrioritiesRoute
  AgentProfileRoute: typeof AgentProfileRoute
  AgentQuizRoute: typeof AgentQuizRoute
  AgentSubscribeRoute: typeof AgentSubscribeRoute
  ApiAgentMatchesRoute: typeof ApiAgentMatchesRoute
  ApiHealthRoute: typeof ApiHealthRoute
  BuyerChatRoute: typeof BuyerChatRoute
  BuyerDetailsRoute: typeof BuyerDetailsRoute
  BuyerEmailRoute: typeof BuyerEmailRoute
  BuyerIntroRoute: typeof BuyerIntroRoute
  BuyerQuizRoute: typeof BuyerQuizRoute
  BuyerResultsRoute: typeof BuyerResultsRoute
  BuyerSummaryRoute: typeof BuyerSummaryRoute
  BuyerUnlockRoute: typeof BuyerUnlockRoute
  ConsumerPrioritiesRoute: typeof ConsumerPrioritiesRoute
  ConsumerQuizRoute: typeof ConsumerQuizRoute
  ConsumerResultsRoute: typeof ConsumerResultsRoute
  SellerChatRoute: typeof SellerChatRoute
  SellerDetailsRoute: typeof SellerDetailsRoute
  SellerEmailRoute: typeof SellerEmailRoute
  SellerIntroRoute: typeof SellerIntroRoute
  SellerQuizRoute: typeof SellerQuizRoute
  SellerResultsRoute: typeof SellerResultsRoute
  SellerSummaryRoute: typeof SellerSummaryRoute
  SellerUnlockRoute: typeof SellerUnlockRoute
  ThemesThemeNameRoute: typeof ThemesThemeNameRoute
  AgentIndexRoute: typeof AgentIndexRoute
  BuyerIndexRoute: typeof BuyerIndexRoute
  ConsumerIndexRoute: typeof ConsumerIndexRoute
  SellerIndexRoute: typeof SellerIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBetaAuthRoute: typeof ApiBetaAuthRoute
  ApiIngestSplatRoute: typeof ApiIngestSplatRoute
  ApiIngestStaticSplatRoute: typeof ApiIngestStaticSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase': {
      id: '/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match-activity': {
      id: '/match-activity'
      path: '/match-activity'
      fullPath: '/match-activity'
      preLoaderRoute: typeof MatchActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beta': {
      id: '/beta'
      path: '/beta'
      fullPath: '/beta'
      preLoaderRoute: typeof BetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/': {
      id: '/seller/'
      path: '/seller'
      fullPath: '/seller/'
      preLoaderRoute: typeof SellerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumer/': {
      id: '/consumer/'
      path: '/consumer'
      fullPath: '/consumer/'
      preLoaderRoute: typeof ConsumerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/': {
      id: '/buyer/'
      path: '/buyer'
      fullPath: '/buyer/'
      preLoaderRoute: typeof BuyerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/': {
      id: '/agent/'
      path: '/agent'
      fullPath: '/agent/'
      preLoaderRoute: typeof AgentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/themes/$themeName': {
      id: '/themes/$themeName'
      path: '/themes/$themeName'
      fullPath: '/themes/$themeName'
      preLoaderRoute: typeof ThemesThemeNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/unlock': {
      id: '/seller/unlock'
      path: '/seller/unlock'
      fullPath: '/seller/unlock'
      preLoaderRoute: typeof SellerUnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/summary': {
      id: '/seller/summary'
      path: '/seller/summary'
      fullPath: '/seller/summary'
      preLoaderRoute: typeof SellerSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/results': {
      id: '/seller/results'
      path: '/seller/results'
      fullPath: '/seller/results'
      preLoaderRoute: typeof SellerResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/quiz': {
      id: '/seller/quiz'
      path: '/seller/quiz'
      fullPath: '/seller/quiz'
      preLoaderRoute: typeof SellerQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/intro': {
      id: '/seller/intro'
      path: '/seller/intro'
      fullPath: '/seller/intro'
      preLoaderRoute: typeof SellerIntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/email': {
      id: '/seller/email'
      path: '/seller/email'
      fullPath: '/seller/email'
      preLoaderRoute: typeof SellerEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/details': {
      id: '/seller/details'
      path: '/seller/details'
      fullPath: '/seller/details'
      preLoaderRoute: typeof SellerDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/chat': {
      id: '/seller/chat'
      path: '/seller/chat'
      fullPath: '/seller/chat'
      preLoaderRoute: typeof SellerChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumer/results': {
      id: '/consumer/results'
      path: '/consumer/results'
      fullPath: '/consumer/results'
      preLoaderRoute: typeof ConsumerResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumer/quiz': {
      id: '/consumer/quiz'
      path: '/consumer/quiz'
      fullPath: '/consumer/quiz'
      preLoaderRoute: typeof ConsumerQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumer/priorities': {
      id: '/consumer/priorities'
      path: '/consumer/priorities'
      fullPath: '/consumer/priorities'
      preLoaderRoute: typeof ConsumerPrioritiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/unlock': {
      id: '/buyer/unlock'
      path: '/buyer/unlock'
      fullPath: '/buyer/unlock'
      preLoaderRoute: typeof BuyerUnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/summary': {
      id: '/buyer/summary'
      path: '/buyer/summary'
      fullPath: '/buyer/summary'
      preLoaderRoute: typeof BuyerSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/results': {
      id: '/buyer/results'
      path: '/buyer/results'
      fullPath: '/buyer/results'
      preLoaderRoute: typeof BuyerResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/quiz': {
      id: '/buyer/quiz'
      path: '/buyer/quiz'
      fullPath: '/buyer/quiz'
      preLoaderRoute: typeof BuyerQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/intro': {
      id: '/buyer/intro'
      path: '/buyer/intro'
      fullPath: '/buyer/intro'
      preLoaderRoute: typeof BuyerIntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/email': {
      id: '/buyer/email'
      path: '/buyer/email'
      fullPath: '/buyer/email'
      preLoaderRoute: typeof BuyerEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/details': {
      id: '/buyer/details'
      path: '/buyer/details'
      fullPath: '/buyer/details'
      preLoaderRoute: typeof BuyerDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/chat': {
      id: '/buyer/chat'
      path: '/buyer/chat'
      fullPath: '/buyer/chat'
      preLoaderRoute: typeof BuyerChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent-matches': {
      id: '/api/agent-matches'
      path: '/api/agent-matches'
      fullPath: '/api/agent-matches'
      preLoaderRoute: typeof ApiAgentMatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/subscribe': {
      id: '/agent/subscribe'
      path: '/agent/subscribe'
      fullPath: '/agent/subscribe'
      preLoaderRoute: typeof AgentSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/quiz': {
      id: '/agent/quiz'
      path: '/agent/quiz'
      fullPath: '/agent/quiz'
      preLoaderRoute: typeof AgentQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/profile': {
      id: '/agent/profile'
      path: '/agent/profile'
      fullPath: '/agent/profile'
      preLoaderRoute: typeof AgentProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/priorities': {
      id: '/agent/priorities'
      path: '/agent/priorities'
      fullPath: '/agent/priorities'
      preLoaderRoute: typeof AgentPrioritiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/peace-pact': {
      id: '/agent/peace-pact'
      path: '/agent/peace-pact'
      fullPath: '/agent/peace-pact'
      preLoaderRoute: typeof AgentPeacePactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/deep-dive': {
      id: '/agent/deep-dive'
      path: '/agent/deep-dive'
      fullPath: '/agent/deep-dive'
      preLoaderRoute: typeof AgentDeepDiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/compliance': {
      id: '/agent/compliance'
      path: '/agent/compliance'
      fullPath: '/agent/compliance'
      preLoaderRoute: typeof AgentComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/chat': {
      id: '/agent/chat'
      path: '/agent/chat'
      fullPath: '/agent/chat'
      preLoaderRoute: typeof AgentChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest/$': {
      id: '/api/ingest/$'
      path: '/api/ingest/$'
      fullPath: '/api/ingest/$'
      preLoaderRoute: typeof ApiIngestSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/beta/auth': {
      id: '/api/beta/auth'
      path: '/api/beta/auth'
      fullPath: '/api/beta/auth'
      preLoaderRoute: typeof ApiBetaAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest/static/$': {
      id: '/api/ingest/static/$'
      path: '/api/ingest/static/$'
      fullPath: '/api/ingest/static/$'
      preLoaderRoute: typeof ApiIngestStaticSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  BetaRoute: BetaRoute,
  LoginRoute: LoginRoute,
  MatchActivityRoute: MatchActivityRoute,
  ShowcaseRoute: ShowcaseRoute,
  SignupRoute: SignupRoute,
  AgentChatRoute: AgentChatRoute,
  AgentComplianceRoute: AgentComplianceRoute,
  AgentDeepDiveRoute: AgentDeepDiveRoute,
  AgentPeacePactRoute: AgentPeacePactRoute,
  AgentPrioritiesRoute: AgentPrioritiesRoute,
  AgentProfileRoute: AgentProfileRoute,
  AgentQuizRoute: AgentQuizRoute,
  AgentSubscribeRoute: AgentSubscribeRoute,
  ApiAgentMatchesRoute: ApiAgentMatchesRoute,
  ApiHealthRoute: ApiHealthRoute,
  BuyerChatRoute: BuyerChatRoute,
  BuyerDetailsRoute: BuyerDetailsRoute,
  BuyerEmailRoute: BuyerEmailRoute,
  BuyerIntroRoute: BuyerIntroRoute,
  BuyerQuizRoute: BuyerQuizRoute,
  BuyerResultsRoute: BuyerResultsRoute,
  BuyerSummaryRoute: BuyerSummaryRoute,
  BuyerUnlockRoute: BuyerUnlockRoute,
  ConsumerPrioritiesRoute: ConsumerPrioritiesRoute,
  ConsumerQuizRoute: ConsumerQuizRoute,
  ConsumerResultsRoute: ConsumerResultsRoute,
  SellerChatRoute: SellerChatRoute,
  SellerDetailsRoute: SellerDetailsRoute,
  SellerEmailRoute: SellerEmailRoute,
  SellerIntroRoute: SellerIntroRoute,
  SellerQuizRoute: SellerQuizRoute,
  SellerResultsRoute: SellerResultsRoute,
  SellerSummaryRoute: SellerSummaryRoute,
  SellerUnlockRoute: SellerUnlockRoute,
  ThemesThemeNameRoute: ThemesThemeNameRoute,
  AgentIndexRoute: AgentIndexRoute,
  BuyerIndexRoute: BuyerIndexRoute,
  ConsumerIndexRoute: ConsumerIndexRoute,
  SellerIndexRoute: SellerIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBetaAuthRoute: ApiBetaAuthRoute,
  ApiIngestSplatRoute: ApiIngestSplatRoute,
  ApiIngestStaticSplatRoute: ApiIngestStaticSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
