apiVersion: v1
kind: Namespace
metadata:
  name: imdbgraph
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: imdbgraph-secrets
  namespace: imdbgraph
spec:
  encryptedData:
    CRON_SECRET: AgBErYYa9rwcQ3xf1Ne1YDw7pWvXBU8TCweoTi0BnSGlKdwSivRpdq1YQGPjZJJPX3Y0tjIJ2Zt2JERE5GljkFZOT2ByAMiG0aO2Tt9OtJMuOsI6GKQ/P2b8Nb/89ddbVvwwmB/5NZICuf/1Ed9GjrvRs0Lm63Nb6sD0d8SJrut5ojTJn8RiapecjHshkIsxxWOcbKQJO9mmYa3EL7Qw1ziMHrQmi6Hk3cXV09o83WnWSP099oWIC+I7czGAoEcw38UvEjfA86ygnA2sb4NkbsC3pTAql6T/U6cm2K5BivUARpfu5L6yHWsqAdIdWPl4+7wv/jN/Yvc08qRgDQBv9170v358/f8pWnuJcMToEj7j4dHNArgQ6c+Ar1m/FnYm+KaristCGv7GX3l+kSKK5IrrXNU1NsY1rT5N6oafLcIQdMNf1SlYsKArFK7DzvmoxSOfluaawlN34PscxqdFLa+y4EmOq/YoUdtRtQ2GZ/boQbS1/CSLrTCzvdZQy6CZiSHrmbfWTxaIsvneDODETm4d3DFOBHC8ccT/xPGZ9VdlkcRkoSPaiCm4AP/uxHSyx71Mg9AZxEvXGvoGtEKukGgKljlE3Zq5jk4mGhcsz2w0mOlQql0G5BOkYyGCAmL63iPWNAPoYbJv9t4FX7q78f5ZrOqb9S+zWY59cz4D9h3b4TTCLOSZNCIgQNMjMP7LEVWkTh5wdMWW04yr7wtgEf4PEVUJ9+mTNdrhp9m8/yEAZN+C2sk=
    DATABASE_URL: AgArQIYw5St//5qLGCdiR32wyz8nJ27uu/HuUEu0GDGu3REr5CA3dxBSF/q2F5F80hyvA417Wt//bgMZw3L0hiBiWmSY3svn90Oc2vRp16wIDOj6nU+BVk2UQdSe7s2rKATne1tOBntu7XaqUNdJKgsJEStTxQHzU+b6GVvLpP/KaBktztLhpfANwfc+5+PZ8dIw3oJ2c4WGY+ko3Dkk88QAa1gITAOLQkKDf+Hf2hkp22TOEOAeOZyu+yaK29Iz+C2YelhBt0EhYRWooItvURc6KxcJEhaTictGmTl8gRyr6tbwBseAG3CJnSb0wgEENODu0Tlpxwr6JRMSwTHsm0xbQnJcbnkbrdFwddBQRPBSzL71S4GViRs3S9Mra2lGMvAdriKa4ZFlFhjPDAiStOiVsCScO7ZHBhG1HLeVziGz3d7gkcwF3qj3F0cne5DoE+C8lI/IXGK0HzsxczZ5O7m4Jw0pTM2anUEbfYl2m1G29AMrz3D2SOxWM6F5Qlk2sCU0u6nnhnxaKL5frdnC2PxFH/qMc9wdIfn17w0y899LOx/+VUh9y10XqqesnhLWYayEQhdLtnoAd+P409yt8yyVRBUNeWIa2bEeTV71WAArnLxFXYv8IE+SzsIGkI+9JQEnpjGMv/tnIkEiEiPvz/3J8OCRZghQ9w2GtwscCNrZ2gVkbIgaihD1Q/yuzCVI25EwafJpZyTShYu0yqtUNEdWqIsGneDY7oGq/hW2PDkSfcGpOuOMn234AilX3vNSymomMnmoE2mLUZtngq8oNYML5tmke1JIu22hEh2SYT+YO61jcZHOuVpZPiuLgGn9rMk1kbIaNJxIWSJfXBLxqb8037Pwbh25ffvRunoAob+FcNcIsBmKNrzzXM6Fv2trkMD0LV50aV8=
  template:
    metadata:
      name: imdbgraph-secrets
      namespace: imdbgraph
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: imdbgraph
  namespace: imdbgraph
spec:
  interval: 10m
  chart:
    spec:
      chart: ./packages/infra/charts/app-release
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 10m
  values:
    app:
      name: imdbgraph
      namespace: imdbgraph
    image:
      repository: aaministack.azurecr.io/imdbgraph
      tag: latest
    host: imdbgraph.ariaamini.com
    envFromSecret: imdbgraph-secrets
