name: apps/portfolio

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'apps/portfolio/**'
      - 'apps/portfolio-e2e/**'
      - 'libs/**'
  push:
    branches:
      - main
    paths:
      - 'apps/portfolio/**'
      - 'apps/portfolio-e2e/**'
      - 'libs/**'

jobs:
  ci:
    permissions:
      contents: write
      pull-requests: write
    uses: ./.github/workflows/ci.yml
    with:
      app_name: 'portfolio'
      vercel_project_id: 'prj_cvx0v2KsnbVwmMWowN55wkUfNksg'
      vercel_org_id: 'team_BMB11Zck0xVJiYVTGXOUqLiz'
      environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'preview' }}
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
