name: Deploy to Vercel

on:
  workflow_call:
    inputs:
      project_id:
        required: true
        type: string
      org_id:
        required: true
        type: string
      app_name:
        required: true
        type: string
    outputs:
      preview_url:
        description: "The URL of the Vercel preview deployment."
        value: ${{ jobs.deploy.outputs.preview_url }}
    secrets:
      VERCEL_TOKEN:
        required: true

permissions:
  contents: read

jobs:
  deploy:
    name: 'Deploy to Vercel'
    runs-on: ubuntu-latest
    env:
      VERCEL_PROJECT_ID: ${{ inputs.project_id }}
      VERCEL_ORG_ID: ${{ inputs.org_id }}
    outputs:
      preview_url: ${{ steps.deploy.outputs.url }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Install Vercel CLI
        run: pnpm add --global vercel@latest
      - name: Pull Vercel Environment Information
        working-directory: ./apps/imdbgraph
        run: vercel pull --cwd ../.. --token=${{ secrets.VERCEL_TOKEN }} --yes --environment=preview 
      - name: Build Project Artifacts
        working-directory: ./apps/imdbgraph
        run: vercel build --cwd ../.. --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        id: deploy
        working-directory: ./apps/imdbgraph
        run: echo "url=$(vercel deploy --cwd ../.. --prebuilt --token=${{ secrets.VERCEL_TOKEN }})" >> $GITHUB_OUTPUT
