name: E2E

on:
  repository_dispatch:
    types:
      - "vercel.deployment.success"
  workflow_dispatch:
    inputs:
      update_snapshots:
        description: "Whether to update the playwright reference screenshots"
        required: false
        type: boolean
        default: false

permissions:
  contents: write

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

jobs:
  run-e2e:
    runs-on: ubuntu-latest
    env:
      APP_NAME: ${{ github.event.client_payload.project.name }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.git.sha }}
      - name: Setup Node
        uses: ./.github/actions/setup
      - name: Run Playwright tests
        working-directory: \
          ./apps/${{ env.APP_NAME }}
        env:
          BASE_URL: ${{ github.event.client_payload.url }}
          VERCEL_AUTOMATION_BYPASS_SECRET: \
            ${{ secrets.VERCEL_AUTOMATION_BYPASS_SECRET }}
        run: pnpm run e2e${{ inputs.update_snapshots && ':update' || '' }}
      - name: Upload Screenshots
        if: success() && inputs.update_snapshots
        uses: actions/upload-artifact@v4
        with:
          name: screenshots-${{ env.APP_NAME }}
          path: "./*/**/e2e/**/*.png"
          retention-days: 1
      - name: Publish Report
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report-${{ env.APP_NAME }}
          path: "./apps/${{ env.APP_NAME }}/playwright-report"
          retention-days: 30

  collect-reports:
    runs-on: ubuntu-latest
    needs: [run-e2e]
    steps:
      - name: Download All Screenshot Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: playwright-report-*
          merge-multiple: true

  commit-screenshots:
    runs-on: ubuntu-latest
    needs: [run-e2e]
    if: inputs.update_snapshots
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Download All Screenshot Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: screenshots-*
          merge-multiple: true
      - name: Commit Screenshots
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add *.png
          git commit -m "Update Screenshots"
          git push
