name: IMDBGraph CI

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'apps/imdbgraph/**'
      - 'apps/imdbgraph-e2e/**'
      - 'libs/**'

permissions:
  contents: write
  pull-requests: write

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Verify
        run: pnpm run verify:ci

  deploy-imdbgraph:
    name: 'Deploy IMDBGraph to Vercel'
    uses: ./.github/workflows/deploy.yml
    with:
      app_name: 'imdbgraph'
      project_id: 'prj_k4hqwb95voxcnozM1DY5zuL0rGHv'
      org_id: 'team_BMB11Zck0xVJiYVTGXOUqLiz'
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

  e2e:
    name: 'End-to-End Playwright UI Tests'
    runs-on: windows-latest
    needs: deploy-imdbgraph
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Install Playwright Browsers
        run: pnpm dlx playwright install --with-deps
      - name: Run Playwright tests
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          BASE_URL: ${{ needs.deploy-imdbgraph.outputs.preview_url }}
        run: pnpm run e2e
      - uses: actions/upload-artifact@v4
        id: artifact-upload
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: '**/apps/*-e2e/playwright-report'
          retention-days: 30
      - name: Comment on PR with report link
        uses: thollander/actions-comment-pull-request@v3
        if: ${{ failure() }}
        with:
          message: |
            ### Playwright visual snapshot differences were detected.
            View the [Playwright report](${{ steps.artifact-upload.outputs.artifact-url }}) to review the visual differences.
            **To approve the snapshot changes and update the snapshots, please comment:** /approve-snapshots
