name: Playwright Tests
run-name: 'Playwright Tests: ${{ github.event.client_payload.project.name }}'

on:
  repository_dispatch:
    types:
      - 'vercel.deployment.success'

jobs:
  run-e2es:
    if: github.event_name == 'repository_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.git.sha }}
      - uses: ./.github/actions/setup
      - name: Install Playwright Browsers
        run: pnpm dlx playwright install --with-deps
      - name: Run Playwright tests
        env:
          BASE_URL: ${{ github.event.client_payload.url }}
        run: pnpm turbo run e2e
      - uses: actions/upload-artifact@v4
        id: artifact-upload
        if: ${{ failure() }}
        with:
          name: playwright-report
          path: 'apps/**/playwright-report'
          retention-days: 30
