name: Update Snapshots on Comment

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
    secrets:
      DATABASE_URL:
        required: false

jobs:
  update-snapshots:
    name: Update Snapshots
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      # Comment on PR
      - name: Get branch of PR
        uses: xt0rted/pull-request-comment-branch@v2
        id: comment-branch
      - name: Comment action started
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            ### Updating snapshots. Click [here](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) to see the status.
      
      # Setup
      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}
      - uses: ./.github/actions/setup
      - name: Install Playwright Browsers
        run: pnpm dlx playwright install --with-deps
      - name: Build
        run: pnpm run build
      # Run
      - name: Run Playwright tests
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          pnpm --filter=${{ inputs.app_name }}-e2e run e2e -- --update-snapshots
      
      # Update screenshots
      - name: Commit and push updated snapshots
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Update e2e snapshots'
      - name: Comment success
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            ### 🎉 Successfully updated and committed Playwright snapshots! 🎉
